export type Category = 'openings' | 'middlegame' | 'endgame' | 'psychology' | 'thinking'
export type Level = 'beginner' | 'intermediate' | 'advanced'

export interface Lesson {
  id: string
  category: Category
  title: string
  subtitle: string
  level: Level
  fen: string
  keyPoints: string[]
  paragraphs: string[]
  famousNote?: string
}

export const LESSONS: Lesson[] = [
  // ── OPENINGS ────────────────────────────────────────────────────
  {
    id: 'open-1', category: 'openings', title: 'The Open Game — 1.e4 e5',
    subtitle: 'Foundation of classical chess', level: 'beginner',
    fen: 'rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2',
    keyPoints: [
      'Controls the center with a pawn immediately',
      'Opens diagonals for queen and king bishop',
      'Leads to sharp, tactical games — best studied first',
      'Best starting point for beginners of all styles',
      'Used by World Champions from Morphy to Kasparov',
    ],
    paragraphs: [
      '1.e4 is the most popular first move in chess, played by Morphy, Fischer, and Kasparov. Black\'s most direct reply is 1...e5, fighting for the center immediately. Both sides seize the center with pawns, opening lines for bishops and queens.',
      'The open game leads to rich tactical battles. White typically plays 2.Nf3 attacking the e5 pawn, and Black defends with 2...Nc6. This is the starting point for the Italian Game (3.Bc4), Ruy Lopez (3.Bb5), and Scotch Game (3.d4). Mastering these three is essential for every player.',
      'Key principle: develop your pieces quickly, castle early, and contest the center. Every move that doesn\'t develop a piece or improve position should be questioned.',
    ],
    famousNote: 'Paul Morphy defeated the Duke of Brunswick in the Opera Game (1858) in just 13 moves after 1.e4. This remains one of chess history\'s most celebrated miniatures demonstrating the power of open-game principles.',
  },
  {
    id: 'open-2', category: 'openings', title: 'The Italian Game',
    subtitle: 'Bc4 — the classical attacking setup', level: 'beginner',
    fen: 'r1bqk1nr/pppp1ppp/2n5/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
    keyPoints: [
      'Bc4 targets the vulnerable f7 pawn',
      'Aims for rapid development and center control',
      'Giuoco Piano: quiet positional battles',
      'Evans Gambit (b4): sharp gambit play',
      'One of the oldest documented openings (1500s)',
    ],
    paragraphs: [
      'After 1.e4 e5 2.Nf3 Nc6, White plays 3.Bc4 — the Italian Game. The bishop on c4 puts immediate pressure on f7, the weakest point in Black\'s starting position. Black most commonly replies 3...Bc5, contesting the center.',
      'The Giuoco Piano ("quiet game" in Italian) arises after 4.c3 preparing d4. Black replies 4...Nf6 attacking e4. These positions are rich in strategic ideas: controlling d5, using the half-open d-file, and trading at the right moment.',
      'Critical idea: the Fried Liver Attack sacrifices a knight on f7 for a devastating attack. Understanding material sacrifice for initiative is one of the Italian\'s most important lessons.',
    ],
    famousNote: 'Magnus Carlsen has used the Italian Game throughout his career, citing its rich positional complexity. At the 2016 World Championship, he used it to outplay Sergey Karjakin in long technical games.',
  },
  {
    id: 'open-3', category: 'openings', title: 'The Ruy Lopez (Spanish Game)',
    subtitle: 'The most theoretically rich opening', level: 'intermediate',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
    keyPoints: [
      'Bb5 indirectly pressures e5 via the Nc6',
      'Named after Bishop Ruy López de Segura (1561)',
      'White seeks long-term positional pressure',
      'Main systems: Closed, Open, Berlin, Marshall Attack',
      'Berlin Defense used by Kramnik to defeat Kasparov in 2000',
    ],
    paragraphs: [
      'The Ruy Lopez (3.Bb5) is arguably the most studied opening in chess. The bishop on b5 creates long-term strategic pressure on Black\'s center without directly winning material immediately.',
      'The Berlin Defense (3...Nf6) was considered drawish until Vladimir Kramnik used it to neutralize Garry Kasparov at the 2000 World Championship. The Closed Spanish (3...a6 4.Ba4 Nf6 5.0-0 Be7) is the most complex main line.',
      'Key strategic idea: White often plays a4 and a5 to undermine Black\'s queenside pawn chain, while Black counterattacks with ...d5 or ...f5. Understanding these long-term pawn breaks is essential.',
    ],
    famousNote: 'Garry Kasparov used the Ruy Lopez as his main weapon for decades. His battles with Karpov in the Ruy Lopez produced some of chess history\'s most instructive games, analyzing both the Berlin and Closed systems to unprecedented depth.',
  },
  {
    id: 'open-4', category: 'openings', title: 'The Sicilian Defense',
    subtitle: 'Black\'s sharpest and most popular reply to 1.e4', level: 'intermediate',
    fen: 'rnbqkbnr/pp1ppppp/8/2p5/4P3/8/PPPP1PPP/RNBQKBNR w KQkq c6 0 2',
    keyPoints: [
      'Most popular defense against 1.e4 at all levels',
      '1...c5 fights for d4 without symmetry',
      'Main variations: Najdorf, Dragon, Scheveningen, Classical',
      'Black often gets queenside counterplay vs White\'s kingside attack',
      'Statistically the most combative opening at grandmaster level',
    ],
    paragraphs: [
      '1...c5 is Black\'s most ambitious response to 1.e4. Instead of mirroring with 1...e5, Black fights for d4 asymmetrically, creating an imbalanced pawn structure: White has more center space; Black has the half-open c-file for counterplay.',
      'The Najdorf Variation (5...a6) is Black\'s most popular defense. Fischer called it the best defense to 1.e4. The a6 move prevents Nb5 and prepares queenside expansion with ...b5. White attacks on the kingside, Black counterattacks on the queenside.',
      'The Dragon Variation (5...g6 followed by ...Bg7) is famous for the Yugoslav Attack: White castles queenside and launches a vicious pawn storm, while Black\'s dragon bishop breathes fire down the long diagonal.',
    ],
    famousNote: 'Bobby Fischer famously said "The Sicilian Defense is the best defense against 1.e4." He used the Najdorf to defeat Boris Spassky in their legendary 1972 World Championship match.',
  },
  {
    id: 'open-5', category: 'openings', title: 'The Queen\'s Gambit',
    subtitle: 'The cornerstone of 1.d4 strategy', level: 'intermediate',
    fen: 'rnbqkbnr/ppp1pppp/8/3p4/2PP4/8/PP2PPPP/RNBQKBNR b KQkq c3 0 2',
    keyPoints: [
      '1.d4 d5 2.c4 — offers a pawn to gain center control',
      'QGA (2...dxc4): White regains the pawn with superior activity',
      'QGD (2...e6): solid structure, long strategic battle',
      'Catalan (g3+Bg2): modern positional variation',
      'Exchange Variation (cxd5): sets up minority attack plan',
    ],
    paragraphs: [
      'The Queen\'s Gambit is not truly a gambit — White\'s c4 pawn can almost always be recaptured. After 2.c4, if Black takes with 2...dxc4, White plays 3.Nf3 followed by Bxc4, regaining the pawn with superior piece activity.',
      'The Queen\'s Gambit Declined (QGD) is one of chess\'s most solid defenses. The key strategic fight is over the e5 and c5 squares. White often targets Black\'s isolated d-pawn (IQP) positions that arise after ...c5 exchanges.',
      'The Catalan Opening (3.g3 4.Bg2) has become extremely popular at grandmaster level. The fianchettoed bishop on g2 exerts long-term pressure on the entire queenside. Anand, Kramnik, and Carlsen have used it extensively.',
    ],
    famousNote: 'Vladimir Kramnik used the QGD Berlin and QGD Cambridge Springs to defeat Garry Kasparov in the 2000 World Championship, ending Kasparov\'s 15-year reign with purely solid, anti-tactical chess.',
  },
  // ── MIDDLEGAME ───────────────────────────────────────────────────
  {
    id: 'mid-1', category: 'middlegame', title: 'The 3 Core Principles',
    subtitle: 'Development, Center Control, King Safety', level: 'beginner',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
    keyPoints: [
      'Develop ALL pieces before attacking',
      'Control the center with pawns and pieces',
      'Castle early — the king is a liability in the center',
      'Don\'t move the same piece twice in the opening',
      'Connect your rooks — they thrive on open files',
    ],
    paragraphs: [
      'Chess has three universal opening principles. First: develop your pieces. Knights before bishops, then castle. A piece on its starting square contributes nothing. Develop toward the center — Nf3 is better than Nh3; Bc4 is better than Ba3.',
      'Second: control the center. The four central squares (e4, e5, d4, d5) are the most important on the board. Pieces in the center have maximum mobility. Even hypermodern openings like the King\'s Indian challenge the center later with ...c5 or ...e5.',
      'Third: castle your king to safety before move 10. Once castled, your king is protected and rooks can connect. Delaying castling to attack usually fails — the opponent\'s counter is faster when you have an uncastled king.',
    ],
    famousNote: 'Wilhelm Steinitz (1st World Champion) was first to formulate positional principles, showing that violating them has concrete consequences. His ideas were revolutionary in the 1880s and remain foundational today.',
  },
  {
    id: 'mid-2', category: 'middlegame', title: 'Pawn Structure & Plans',
    subtitle: 'Pawns are the soul of chess — Nimzowitsch', level: 'intermediate',
    fen: 'r1bq1rk1/pp2ppbp/2n2np1/2pp4/3PP3/2N2N2/PPP1BPPP/R1BQ1RK1 w - - 0 8',
    keyPoints: [
      'Isolated pawns are weak but grant piece activity',
      'Doubled pawns create weak squares but open files',
      'Passed pawns must be pushed — they are future queens',
      'Backward pawns on open files are chronic weaknesses',
      'The pawn structure determines your long-term plan',
    ],
    paragraphs: [
      'Unlike pieces, pawns cannot move backward — every pawn move creates permanent structural consequences. The Isolated Queen\'s Pawn (IQP) on d4/d5 is a perfect example: it\'s a weakness (no pawn defends it) but grants mobile piece advantage and control of e5/c5 outposts.',
      'Passed pawns — no enemy pawn blocking them or on adjacent files — are enormously powerful in endgames. A connected passed pawn pair on d5/e5 is nearly irresistible. Tarrasch\'s rule: "A knight on d5 supported by a pawn is worth as much as a rook."',
      'Pawn breaks are critical tools. In the King\'s Indian, Black\'s standard break is ...e5-e4 or ...f5-f4. In the French, ...c5 breaks White\'s center. Identify these breaks in your openings and know both sides\' thematic plans.',
    ],
    famousNote: 'Aron Nimzowitsch\'s "My System" (1925) revolutionized chess by explaining pawn weaknesses, blockade, and the passed pawn. His concepts are still taught in every FIDE coach certification program.',
  },
  {
    id: 'mid-3', category: 'middlegame', title: 'Piece Activity & Coordination',
    subtitle: 'Good pieces always beat bad pieces', level: 'intermediate',
    fen: 'r4rk1/ppp2pp1/2n4p/3pq3/3N4/2P1P3/PP3PPP/R1BQ1RK1 w - - 0 12',
    keyPoints: [
      'Knight on d5/d4 with pawn support = outpost powerhouse',
      'Rooks belong on open files — control the initiative',
      'Bishop pair in open positions is a serious advantage',
      'Bad bishop: blocked by its own pawns — a permanent weakness',
      'Piece activity often matters more than material count',
    ],
    paragraphs: [
      'A knight on d5 supported by a pawn controls 8 squares, cannot be attacked by opposing pawns, and disrupts the enemy position. The key concept is the "outpost": a square that cannot be attacked by enemy pawns. A knight there often dominates the game.',
      'Rooks belong on open and half-open files. The player who controls the d-file has a lasting initiative. Doubled rooks create devastating battery attacks. "A rook needs an open file like a fish needs water." — Nimzowitsch.',
      'The bishop pair (having both bishops when the opponent has a bishop and knight) is a significant advantage in open positions. Two bishops cover all colors and improve as more pieces are traded. Fischer called the bishop pair "like having two queens."',
    ],
    famousNote: 'José Raúl Capablanca (World Champion 1921-1927) mastered piece activity. He often "simplified" to positions where his pieces were perfectly placed and opponents\' were passive — then converted these small advantages systematically.',
  },
  {
    id: 'mid-4', category: 'middlegame', title: 'King Safety & Pawn Storms',
    subtitle: 'The king is everything — protect it', level: 'intermediate',
    fen: 'r1bq1rk1/ppp2ppp/2n5/3pp3/4P3/2N2N2/PPP2PPP/R1BQK2R w KQ - 0 8',
    keyPoints: [
      'Castle before move 10 — every tempo in the center is dangerous',
      'Avoid unnecessary pawn moves in front of your castled king',
      'Opposite-side castling = mutual pawn storms — speed wins',
      'Same-side castling = quieter, positional game',
      'Never castle into an obvious attack',
    ],
    paragraphs: [
      'King safety overrides all other considerations. Castle before move 10. The king needs a wall of pawns (f2, g2, h2 if castled kingside). Any move that disturbs this wall should be carefully considered — it may never recover.',
      'When players castle on opposite sides, both attack the enemy king with pawns: White advances h2-h4-h5, Black advances a7-a5-a4. The player who attacks faster wins. Every tempo is critical. Even a half-tempo blunder can lose.',
      'When both players castle on the same side, the game is more positional. Piece activity, pawn breaks, and prophylaxis matter more than speed. Weakening your king with ...h6 or g4 costs you — opponents can later sacrifice to open lines.',
    ],
    famousNote: 'Mikhail Tal, "the Magician from Riga," World Champion 1960-61, was a genius at sacrificing against the uncastled king. "You must take your opponent into a deep dark forest where 2+2=5, and the path out is only wide enough for one." — Tal.',
  },
  {
    id: 'mid-5', category: 'middlegame', title: 'Tactical Patterns Every Player Must Know',
    subtitle: 'Combinations are the currency of chess', level: 'advanced',
    fen: 'r1b1k2r/pppp1ppp/2n5/2b1p3/2B1P3/3P1N2/PPP2PPP/RNBQ1K1R w kq - 0 6',
    keyPoints: [
      'Fork: one piece attacks two pieces simultaneously',
      'Pin: a piece is immobilized exposing a valuable piece behind it',
      'Skewer: attack the more valuable piece first, take what\'s behind',
      'Discovered attack: moving one piece reveals another\'s attack',
      'Zwischenzug: insert a forcing move before the expected reply',
    ],
    paragraphs: [
      'Tactics are the building blocks of chess. Learn these patterns until they are reflexive: the fork (knight attacks king and queen — take the queen); the pin (bishop on g5 pins Nf6 to Qd8 — knight cannot move safely); the skewer (rook attacks Qe7, queen moves, rook takes Be8).',
      'Discovered attacks are among the most powerful tactical motifs. When a piece moves away from a line, it "discovers" the attack of the piece behind it. A discovered check is particularly fearsome — the moving piece can go anywhere while the king must respond to check.',
      'The Zwischenzug (German: "in-between move") inserts a forcing move instead of the expected reply. Your opponent must respond first, then you handle the original situation — often winning material or escaping danger.',
    ],
    famousNote: 'Tactics training is the fastest path to improvement. Karpov recommended solving 3-5 tactical puzzles daily as his primary training method. FIDE research shows 1,000+ puzzles solved improves average rating by 150-200 ELO points.',
  },
  // ── ENDGAME ──────────────────────────────────────────────────────
  {
    id: 'end-1', category: 'endgame', title: 'King & Pawn vs. King',
    subtitle: 'The fundamental endgame every player must master', level: 'beginner',
    fen: '8/8/3k4/8/3K4/3P4/8/8 w - - 0 1',
    keyPoints: [
      'Opposition: kings facing each other with one square between them',
      'Attacking king must reach the 6th rank in front of the pawn',
      'Edge pawns (a/h file) often draw — king reaches the corner',
      'Rule of the square: if the king enters the square, it catches the pawn',
      'Having the opposition is usually decisive',
    ],
    paragraphs: [
      'King and Pawn vs. King is the fundamental endgame. The key concept: "opposition" — two kings oppose each other when they face each other with exactly one square between them. The player who does NOT have to move when opposition occurs has the advantage.',
      'Winning method: your king must march in front of the pawn, reaching the 6th rank (3rd rank for Black). From there, you achieve zugzwang: your opponent must give way, then you advance the pawn safely to promotion.',
      'Critical exception: edge pawns (a-pawn and h-pawn) often draw even with the opposition. If the defending king reaches the corner in front of the pawn (a8 for White\'s a-pawn), it draws — the attacking king cannot dislodge it without stalemating.',
    ],
    famousNote: 'Reuben Fine wrote: "The player who has not studied K+P vs. K has not yet begun to understand chess." Every world champion has had this endgame mastered before age 12.',
  },
  {
    id: 'end-2', category: 'endgame', title: 'Basic Checkmates: K+Q and K+R',
    subtitle: 'Force the opponent to the edge — never stalemate', level: 'beginner',
    fen: '8/8/8/8/3k4/8/8/2K1Q3 w - - 0 1',
    keyPoints: [
      'K+Q vs K: queen restricts king to edge, king assists, deliver checkmate',
      'K+R vs K: rook cuts off king, your king drives it to the edge',
      'NEVER stalemate — always leave the opponent a legal move',
      'K+Q: checkmate in at most 10 moves from any position',
      'K+R: checkmate in at most 16 moves from any position',
    ],
    paragraphs: [
      'Queen checkmate: the queen restricts the enemy king to progressively smaller zones. When the king is on the edge, bring your king close to assist. The queen gives check, and your king covers escape squares. Key danger: avoid stalemate.',
      'Rook checkmate requires more precision but the same concept: use the rook to cut the king off from ranks or files, then drive it to the edge with your king. The "Lawnmower" technique — the rook systematically cutting across the board — is the clearest method.',
      'Classic stalemate trap in K+Q: 1.Qa5+ Kb1 2.Qb4?? — stalemate! Instead: 2.Kb3 Kc1 3.Qa1#. Always check if the king has any legal moves before giving check. Stalemate is one of the most common ways to throw away a won game.',
    ],
    famousNote: 'FIDE Trainers require all Level 1 coaches to demonstrate these checkmates in under 20 moves. Failure to convert a K+Q win is considered a "catastrophic technical error" in professional tournament play.',
  },
  {
    id: 'end-3', category: 'endgame', title: 'Rook Endings: Lucena & Philidor',
    subtitle: 'The two most important rook positions in chess', level: 'intermediate',
    fen: '1K1k4/1P6/8/8/8/8/8/r1R5 w - - 0 1',
    keyPoints: [
      'Lucena: winning technique when pawn is on 7th rank (build a bridge)',
      'Philidor: drawing technique — rook on 6th rank, then give side checks',
      'Rook belongs BEHIND the passed pawn — yours or the enemy\'s',
      'Tarrasch\'s rule: rook behind the passed pawn',
      'Rook endgames are drawn more often than any other piece ending',
    ],
    paragraphs: [
      'The Lucena Position: your king is in front of the pawn, your rook cuts off the enemy king. Winning method — "building a bridge": your rook gives checks to drive the enemy king away, then the pawn advances, then your rook cuts off the king on the 4th rank so your king steps out.',
      'The Philidor Position: the defender\'s drawing technique. Your rook starts on the 6th rank. When the enemy king advances, you switch to giving checks from the side (from the 1st rank). This draws even when a pawn behind — the key insight that saves many rook endings.',
      'Tarrasch\'s rule: "Place your rook behind a passed pawn — yours to push it, your opponent\'s to stop it." This single rule will save and win many games. Rook in front of or beside a passed pawn is weak; rook behind it is strong.',
    ],
    famousNote: 'At the 2018 World Championship, Magnus Carlsen held a drawn rook endgame against Fabiano Caruana using the Philidor technique under extreme time pressure — proving even world champions must know these fundamentals.',
  },
  {
    id: 'end-4', category: 'endgame', title: 'The Square Rule & Passed Pawns',
    subtitle: 'Can the king catch the pawn? Calculate in 2 seconds', level: 'intermediate',
    fen: '8/8/8/3p4/8/3P4/3K4/5k2 w - - 0 1',
    keyPoints: [
      'Draw a square from the pawn to the promotion square',
      'If the enemy king can step INTO the square on its turn — the pawn is caught',
      'If not — the pawn queens',
      'Connected passed pawns on 5th/6th rank beat a rook',
      'Two connected passers are worth more than a rook in many endings',
    ],
    paragraphs: [
      'The "Rule of the Square" determines if a king can catch a passed pawn without calculation. Draw a diagonal from the pawn\'s square to the promotion square forming a square. If the enemy king can reach any square inside on its next move, the pawn will be caught.',
      'For example: White pawn on e5, enemy king on a1. Count the pawn\'s distance to e8: 3 moves. The square extends 3 files to the right. Can the black king reach h5, h6, h7, h8 in one move? If no, the pawn queens. This takes 2 seconds once internalized.',
      'Connected passed pawns in pairs are devastating in endgames. Two connected passed pawns on the 6th rank beat a rook — the defending rook cannot stop both simultaneously. Creating connected passers should be a primary endgame goal.',
    ],
    famousNote: 'Paul Keres wrote: "The first principle of endgame technique is to create a passed pawn. The second is to advance it. The third is to promote it." Simple but profound — and the foundation of endgame strategy.',
  },
  {
    id: 'end-5', category: 'endgame', title: 'Minor Piece Endgames',
    subtitle: 'Bishop vs Knight — knowing which is better', level: 'advanced',
    fen: '8/5p2/6kp/5p2/5P2/6KP/5P2/3B4 w - - 0 1',
    keyPoints: [
      'Bishop is better in open positions — covers long diagonals instantly',
      'Knight is better in closed positions — fixed pawn structures, outposts',
      '"Good" bishop: pawns are on the opposite color',
      '"Bad" bishop: blocked by own pawns on same color',
      'Two bishops in an open endgame: nearly always winning',
    ],
    paragraphs: [
      'The character of the pawn structure determines which minor piece is superior. Bishops excel when pawns are on both sides of the board — they switch flanks instantly. Knights must slowly hop across the board. Bishops are strongest in open positions with mobile pawns.',
      'Knights excel in closed structures with locked pawns. A centralized knight on an outpost that cannot be attacked by enemy pawns is often worth as much as a rook. Given enough time, a knight can reach every square; a bishop is permanently restricted to one color.',
      'The "bad bishop" is a chronic weakness. If your bishop is on light squares and all your pawns are on light squares too, the bishop is imprisoned by its own army. Solution: trade it off, or reorganize pawns to the opposite color.',
    ],
    famousNote: 'Anatoly Karpov was widely considered the finest endgame technician of the 20th century. His ability to exploit the bishop vs. knight imbalance was legendary in his World Championship matches against Kasparov.',
  },
  // ── PSYCHOLOGY ───────────────────────────────────────────────────
  {
    id: 'psy-1', category: 'psychology', title: 'Managing Time Pressure',
    subtitle: 'Don\'t lose on the clock — time is a chess skill', level: 'intermediate',
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    keyPoints: [
      'Time pressure degrades calculation quality dramatically',
      'Use most thinking time in the middlegame, not the opening',
      'In time trouble: play candidate moves, avoid tactical complexity',
      'Reserve time for critical moments, spend little on known positions',
      'When opponent is in time trouble: keep the position complex',
    ],
    paragraphs: [
      'Time management is a chess skill as important as tactics. Most tournament games are lost on the clock, not on the board. The most common mistake: spending too much time in the opening (memorized positions) and running short in the critical middlegame. Budget your time appropriately.',
      'When YOU are in time pressure: identify the 2-3 most reasonable moves in 5 seconds, eliminate obvious blunders, and play the safest-looking option. Avoid calculating long combinations — you will likely miscalculate. Simplify when possible.',
      'When YOUR OPPONENT is in time pressure: do NOT simplify. Keep the position as complex as possible. Give them difficult decisions on every move. Every extra complication is another chance for them to err under clock pressure.',
    ],
    famousNote: 'Bobby Fischer had all major opening variations memorized through move 25+, rarely getting into time trouble. At the 1972 World Championship, Fischer made Spassky spend far more time than him in every game through deep opening preparation.',
  },
  {
    id: 'psy-2', category: 'psychology', title: 'Playing Against Stronger Opponents',
    subtitle: 'Maximize results as the underdog', level: 'beginner',
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    keyPoints: [
      'Solid defense makes stronger players work hard for every point',
      'Avoid sharp positions with lots of forced lines — they excel there',
      'Choose solid openings — make them prove their superiority slowly',
      'Never panic or give up pieces without concrete compensation',
      'Every draw against a higher-rated player is a moral victory',
    ],
    paragraphs: [
      'Against a stronger opponent, your goal changes: not necessarily to win, but to not lose on move 15 to a tactical blunder. Choose solid, classical openings that don\'t allow the opponent to use deep preparation. The Petroff Defense (1.e4 e5 2.Nf3 Nf6) is ultra-solid for this reason.',
      'Stronger players thrive on complexity — they calculate further and more accurately. Counter-strategy: reduce complexity. Trade pieces when reasonable (especially queens). Aim for equal endgames — in simplified positions, technique matters more than raw calculation.',
      'Never give up psychologically. A drawn position where you believe you are losing is often simply equal. Stronger players sometimes try speculative attacks that aren\'t objectively correct, hoping you panic. The correct response: calmly refute the attack.',
    ],
    famousNote: 'Ulf Andersson, one of history\'s greatest defensive players, routinely drew against opponents 200 ELO points higher through solid play and endgame technique. FIDE coaches use his games as the definitive "how to defend" teaching examples.',
  },
  {
    id: 'psy-3', category: 'psychology', title: 'The Art of Defense',
    subtitle: 'Finding the defensive resource that always exists', level: 'advanced',
    fen: 'r4rk1/ppp1qppp/2n5/3p4/8/2P1BN2/PP3PPP/R2QK2R w KQ - 0 15',
    keyPoints: [
      'Find the critical defensive resource — it almost always exists',
      'Active defense is usually better than passive defense',
      'Trade off the attacker\'s most dangerous piece',
      'Create counterplay — a distraction is as good as a defense',
      'In extreme danger, sacrifice material to reach a safe endgame',
    ],
    paragraphs: [
      'Defense is an underrated skill. Many players assume they are losing when under attack, when the position is actually defensible. First principle: look for the "defensive resource" — the move that refutes the attack. It might be a counter-sacrifice, a desperate check, or a Zwischenzug that upends the opponent\'s plan.',
      'Active defense is often better than passive defense. Instead of moving backward hoping for the best, attack yourself. If your opponent attacks with Ra1-a4, consider ...b5-b4 creating your own threat. This forces the opponent to recalculate — and recalculation leads to errors.',
      'In desperate situations, material sacrifice to reach a safe endgame is sometimes correct. If being mated in 3, give up your rook to reach a rook-down endgame — at least it\'s a fight. Petrosian held many "hopelessly lost" positions this way.',
    ],
    famousNote: '"Iron Tigran" Petrosian (World Champion 1963-1969) was the greatest defensive player in chess history. He would eliminate attacking chances 10 moves before they became threats. FIDE ranked him the best defensive player of the 20th century.',
  },
  {
    id: 'psy-4', category: 'psychology', title: 'Converting Winning Positions',
    subtitle: 'The hardest skill: winning the won game', level: 'advanced',
    fen: 'r4rk1/pp3ppp/2n1p3/q1Pp4/3P4/1QN2N2/PP3PPP/R4RK1 w - - 0 18',
    keyPoints: [
      'Don\'t look for the winning move — look for the clearest move',
      'Simplify when possible: trade to a winning endgame',
      'Don\'t give your opponent counterplay or activity',
      'Winning advantage disappears if you play ambitiously',
      '"When you have a winning position, winning is a technicality" — Karpov',
    ],
    paragraphs: [
      'Converting a winning position is psychologically harder than it sounds. Many players try to win "beautifully" — looking for a brilliant combination when a simple move wins cleanly. The result: they miss the simple continuation, drift into complexity, and let the opponent escape.',
      'Karpov\'s method: when ahead, ask "How can I improve my worst-placed piece?" Make the simplest improvement move every turn. Don\'t give your opponent counterplay. Trade piece by piece. Create no weaknesses. This grinding approach is psychologically devastating.',
      'Avoid "winning with style" syndrome. The most efficient win is always the correct win. If Ra4 wins material, play Ra4 — don\'t look for the fancier Rxh7+. The moment you start thinking about playing impressively instead of correctly, you risk throwing away the win.',
    ],
    famousNote: 'Anatoly Karpov was the supreme master of converting small advantages — his "boa constrictor chess" gradually squeezed opponents until they had no moves. He won 5 World Championship matches and 160+ international tournaments with this philosophy.',
  },
  {
    id: 'psy-5', category: 'psychology', title: 'Creating Complexity as a Weapon',
    subtitle: 'Use chaos strategically — like Tal', level: 'intermediate',
    fen: 'r1bq1rk1/pp3ppp/2n1pn2/2pp4/3P4/2N1PN2/PPQ2PPP/R1B2RK1 w - - 0 10',
    keyPoints: [
      'Complexity favors the player with better nerves and calculation',
      'When losing: complicate to create practical chances',
      'When winning: simplify to convert the advantage',
      'Sacrifice material for dynamic play when the position justifies it',
      'Never sacrifice "by hope" — calculate concretely first',
    ],
    paragraphs: [
      'Complexity is a double-edged sword. In a worse position, complicating gives you practical chances — your opponent might miscalculate in chaos. Magnus Carlsen, even when technically worse, often keeps pieces on the board and creates multiple threats simultaneously.',
      'When you are winning, the opposite applies: simplify. Trade pieces, reach a winning endgame, and convert technically. Many games are lost by players who remain in complex middlegames when they could simply trade to a winning endgame. Kasparov called this "knowing when to stop attacking and start converting."',
      'The decision of when to sacrifice material for dynamic play is one of chess\'s deepest questions. Sacrifice when you can calculate clearly to a winning position, or when your position is so passive that a pawn sacrifice buys real activity. Never sacrifice "by hope."',
    ],
    famousNote: 'Mikhail Tal (World Champion 1960-61) was the king of complexity. His sacrifices were brilliant, sometimes speculative, always terrifying to face. He once said: "There are two types of sacrifices: correct ones and mine." His games are required study for FIDE Trainer certification.',
  },
  // ── THINKING ─────────────────────────────────────────────────────
  {
    id: 'think-1', category: 'thinking', title: 'Candidate Moves — How GMs Think',
    subtitle: 'Kotov\'s method: the systematic approach to calculation', level: 'intermediate',
    fen: 'r1bq1rk1/pp2ppbp/2n2np1/2pp4/3PP3/2N2N2/PPP1BPPP/R1BQK2R w KQ - 0 8',
    keyPoints: [
      'Step 1: Identify ALL candidate moves before calculating any',
      'Step 2: Calculate each candidate to a leaf position',
      'Step 3: Compare leaf positions to find the best',
      'Never go back and reconsider mid-calculation — this causes time trouble',
      'Kotov\'s "tree of analysis" is the basis of all FIDE training',
    ],
    paragraphs: [
      'Alexander Kotov\'s "Think Like a Grandmaster" (1971) described a systematic method. Step 1: Before calculating any move, identify ALL candidate moves — usually 2-4. Step 2: Calculate each down to a "leaf" — a position you can clearly evaluate. Step 3: Compare the leaves and choose the best.',
      'The critical rule: once you start calculating a candidate, go to the end of that branch before switching to another. Jumping between candidates wastes time recalculating the same lines — Kotov called this "shuffling." Discipline: finish analyzing candidate A before starting candidate B.',
      'Practical application: look at ALL threats on both sides first. Identify the 2-3 most forcing moves (checks, captures, serious threats). Calculate. Then ask: "Have I missed any forcing reply?" This prevents the most common blunder — missing a simple tactical counter to your planned move.',
    ],
    famousNote: 'Kotov\'s "Think Like a Grandmaster" introduced "candidate moves" to chess education and is mandatory reading in Russian chess academies. It remains one of the most important chess training books ever published.',
  },
  {
    id: 'think-2', category: 'thinking', title: 'Silman\'s Imbalances',
    subtitle: 'What to look for when there are no obvious tactics', level: 'intermediate',
    fen: 'r1b2rk1/pp2ppbp/1qn2np1/2pp4/3P4/2N2NB1/PPQ1PPPP/R4RK1 w - - 0 11',
    keyPoints: [
      'Material: who is ahead in piece count/value?',
      'Pawn structure: weaknesses? Passed pawns? Open files?',
      'Piece activity: whose pieces are doing more work?',
      'King safety: who is more exposed?',
      'Space: who controls more of the board?',
    ],
    paragraphs: [
      'Jeremy Silman\'s "How to Reassess Your Chess" introduced "imbalances" — a systematic way to evaluate any position. Rather than calculating everything, identify concrete features: material balance, pawn structure, piece activity, king safety, space, and initiative. The player with more positive imbalances has the better position.',
      'Practical use: after your opponent\'s move, assess all imbalances. Who has the bishop pair? More active rooks? A passed pawn? A weak isolated pawn? After listing the imbalances, your plan becomes clear: improve your positives and exploit their weaknesses.',
      'The most important imbalance is usually "piece activity." A player with an active bishop, rooks on open files, and centralized knights against a passive opponent will almost always win even with equal material. Notice when your pieces are passive and improve them immediately.',
    ],
    famousNote: '"How to Reassess Your Chess" by Jeremy Silman is considered the best book for club-level improvement (1200-2000 ELO). According to FIDE coach surveys, it has helped more players break the 2000 barrier than any other single training resource.',
  },
  {
    id: 'think-3', category: 'thinking', title: 'Prophylaxis — Thinking for Your Opponent',
    subtitle: 'Prevent threats before they arise', level: 'advanced',
    fen: '2rq1rk1/pp2ppbp/3p1np1/3P4/3QP3/2N2N2/PP3PPP/R1B2RK1 w - - 0 14',
    keyPoints: [
      '"What does my opponent WANT to do?" — ask before every move',
      'Prevent their best plan before executing your own',
      'Prophylactic moves look "quiet" but are deeply strategic',
      'Nimzowitsch coined the term — means "prevention" in Greek',
      'The greatest players make prophylaxis automatic',
    ],
    paragraphs: [
      'Prophylaxis is the skill separating good players from great ones. Before any move, ask: "What does my opponent want to do?" "What is their best plan?" "Can I prevent it at minimal cost?" If yes, do so first — even delaying your own attack to stop theirs.',
      'Nimzowitsch wrote: "The prevention of any freeing move by the opponent should be considered even when such a move cannot be made at once." Stop problems before they arise. Classic prophylaxis: when your opponent has a bishop pair, keep the position closed. When they have a passed pawn, blockade it immediately.',
      'The most common prophylaxis failure: tunnel vision on your own attack while the opponent builds a devastating counter. Before each move in your attack, scan: "Is there anything my opponent threatens that I\'m ignoring?" This habit alone saves many games.',
    ],
    famousNote: 'Tigran Petrosian was the greatest prophylactic player in history, preventing opponent plans 10 moves before they became threats. His 1969 World Championship match against Boris Spassky showcased prophylaxis at the absolute highest level.',
  },
  {
    id: 'think-4', category: 'thinking', title: 'Visualization & Calculation',
    subtitle: 'Seeing the board clearly in your mind', level: 'intermediate',
    fen: 'r1bqkb1r/ppp2ppp/2n2n2/3pp3/4P3/2N2N2/PPPP1PPP/R1BQKB1R w KQkq - 0 5',
    keyPoints: [
      'Blindfold chess trains visualization fastest',
      'Calculate concrete variations: "If I play X, they play Y, I play Z..."',
      'Always check: can my opponent give check? Capture? Threaten mate?',
      'The "tree check": scan your final position for hanging pieces',
      'Reading chess books WITHOUT a board builds visualization skill',
    ],
    paragraphs: [
      'Visualization — seeing the position in your mind without moving pieces — is the foundation of calculation. Every 5-move combination requires visualizing the board 5 moves ahead. Train this skill: start with 1-move puzzles, progress to 3-move, then 5-move combinations.',
      'Powerful training exercise: replay your own games mentally without looking at the board. Start from the initial position and "see" each move in your mind. When you lose track of the position, you\'ve found your calculation depth limit — and that\'s what to train next.',
      'The "tree check" is mandatory. After calculating a combination, ask: in my final position, are any of my pieces hanging? Is my king in check? Can the opponent make a Zwischenzug I haven\'t considered? Many combinations fail because of this overlooked final check.',
    ],
    famousNote: 'In 1925, Alekhine played 28 simultaneous blindfold games, winning 22. Magnus Carlsen regularly plays blindfold chess in exhibitions. FIDE recommends blindfold training for all players above 1600 ELO as the fastest way to improve calculation depth.',
  },
  {
    id: 'think-5', category: 'thinking', title: 'Your Thinking Routine — Step by Step',
    subtitle: 'A systematic process for every single move', level: 'beginner',
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    keyPoints: [
      'Step 1: After opponent\'s move — what changed? Any new threats?',
      'Step 2: What is my long-term plan in this position?',
      'Step 3: Identify candidate moves (2-4 options)',
      'Step 4: Calculate each candidate thoroughly',
      'Step 5: Before moving — BLUNDER CHECK: any hanging pieces?',
    ],
    paragraphs: [
      'A thinking routine eliminates blunders. After every opponent move: (1) Why did they play that? What threat did it create? (2) What is MY plan — which side do I play on, what pawn break do I want? (3) What are my 2-4 candidate moves? (4) Calculate each carefully. (5) Before moving — the "blunder check": is anything hanging? Am I moving into a tactic?',
      'The blunder check prevents the most common and painful chess mistake: missing a simple one-move reply. Before executing your plan, spend 5 seconds asking: "What is my opponent\'s BEST reply to this move? Can they capture something? Give check? Threaten mate?" This habit alone eliminates 70% of tournament blunders.',
      'Routine builds consistency. Players who think systematically play at their actual strength every game. Players who "wing it" play brilliantly sometimes and terribly other times. Professional coaches rank "thinking routine" as the single most impactful training habit for players below 2000 ELO.',
    ],
    famousNote: 'FIDE certified coaches teach this exact 5-step routine as the foundation of improvement at all levels. Players who implement it consistently typically gain 100-200 ELO in 6-12 months of tournament play.',
  },

  // ── MIDDLEGAME ELITE (FIDE 3200+) ────────────────────────────────
  {
    id: 'mid-e1', category: 'middlegame',
    title: 'The Positional Exchange Sacrifice',
    subtitle: 'Rook for minor piece — buying permanent structural dominance',
    level: 'advanced',
    fen: 'r2q1rk1/pp1nbppp/2p1pn2/3p4/3P4/2NBP3/PPQ1NPPP/R4RK1 w - - 0 12',
    keyPoints: [
      'Sacrifice Rook for Bishop/Knight to gain a permanent positional advantage',
      'Petrosian pioneered it; Carlsen and Kramnik use it routinely at 2800+',
      'Valid compensation: dominant outpost, chronic pawn weakness, passed pawn, or bishop pair',
      'The exchanged minor piece must have no route to activity — its dominance must be permanent',
      'Never sacrifice "routinely" — calculate at least 10 moves of concrete consequences',
    ],
    paragraphs: [
      'The positional exchange sacrifice (giving Rook for Bishop or Knight) is the hallmark of world-class positional chess. You concede a rook (5 pts) for a minor piece (3 pts) but gain something material counting cannot measure: a dominant knight on an outpost that cannot be dislodged, a bishop controlling an entire flank, or a structural weakness in the enemy camp that decides the game 20 moves later. Petrosian, Kramnik, and Carlsen have all made it a cornerstone weapon at world-championship level.',
      'The three criteria for a sound exchange sacrifice: (1) The received piece or outpost must be truly dominant — not merely "slightly better." (2) The rook you give must have limited activity in this specific position. (3) There is no way for the opponent to return the material while also solving their structural problems. If all three criteria are met, the exchange sacrifice is correct even when engines initially flag it as slightly worse.',
      'The most instructive case: Petrosian vs. Spassky, World Championship 1966. Petrosian sacrificed the exchange on move 26, creating a knight domination on d5 supported by a pawn that proved more powerful than the opponent\'s rooks for the next 30 moves. Spassky said: "I had no plan against it." That is the defining quality of a great exchange sacrifice — it leaves the opponent without a constructive counterplan.',
    ],
    famousNote: 'Magnus Carlsen vs. Anand, World Championship 2013 Game 9: Carlsen sacrificed the exchange for a dominant bishop and passed pawn, then converted the resulting domination in a famous endgame. His preparation specifically included Petrosian\'s exchange sacrifice games from the 1960s — a direct bridge between eras of world champions.',
  },
  {
    id: 'mid-e2', category: 'middlegame',
    title: 'The Minority Attack',
    subtitle: 'Using fewer pawns to engineer a permanent weakness',
    level: 'advanced',
    fen: 'r1bq1rk1/pp3ppp/2n1pn2/2pp4/3P4/2N1BN2/PPQ1PPPP/R4RK1 w - - 0 10',
    keyPoints: [
      'Advance 2 pawns against 3 to create an isolated or backward pawn target',
      'Classic in Queen\'s Gambit Exchange Variation: b4-b5-bxc6',
      'The created weakness must be permanent — pieces must anchor before the attack begins',
      'Timing is everything: the queenside advance must come before the opponent activates',
      'Black\'s counter: kingside counterplay must come before the c-pawn becomes terminal',
    ],
    paragraphs: [
      'The Minority Attack is one of chess\'s most sophisticated strategic plans. In the Queen\'s Gambit Exchange, White has 2 queenside pawns (a2, b2) against Black\'s 3 (a7, b7, c6). White advances b4-b5, creating a backward c6-pawn or forcing structural damage. The weakness — isolated, backward, or doubled — becomes a long-term target that ties down Black\'s pieces to passive defense.',
      'The winning procedure after creating the weakness: press it from multiple angles simultaneously. A rook on the c-file, a knight on d4 or e5, and a bishop on the long diagonal create irresistible convergent pressure on c6/c5. The defending pieces become hopelessly passive and eventually collapse under the weight of zugzwang. This exact mechanism appears in virtually every high-level Queen\'s Gambit Exchange game.',
      'Black\'s strategic counter: kingside counterplay must come fast. The moment White secures b5, Black must push ...f5-f4 or ...e5, opening lines toward the White king before the c-pawn becomes terminal. This is the fundamental strategic tension in the Exchange QGD — a race between White\'s queenside pressure and Black\'s kingside attack. At 2800+ level, opening preparation often revolves entirely around the specific timing of b4-b5 versus ...f5.',
    ],
    famousNote: 'Anatoly Karpov elevated the Minority Attack to a systematic weapon. In the 1984-85 World Championship against Kasparov, he converted the Exchange QGD Minority Attack in multiple games. Kasparov\'s eventual answer — switching to the Grünfeld Defense — was specifically designed to avoid Minority Attack pawn structures entirely.',
  },
  {
    id: 'mid-e3', category: 'middlegame',
    title: 'The Two Weaknesses Principle',
    subtitle: 'How world champions squeeze blood from stone',
    level: 'advanced',
    fen: '2r2rk1/pp2bppp/2n1p3/q1Pp4/3P4/1Q2BN2/PP3PPP/R4RK1 w - - 0 16',
    keyPoints: [
      'One weakness is often defensible; two distant weaknesses are usually fatal',
      'Create the first weakness, apply pressure, then open a second front on the other wing',
      'The defender\'s pieces cannot guard two distant targets simultaneously',
      '"Overload" the defense: force defensive pieces to guard two targets at once',
      'Zugzwang is often the mechanism — any move worsens one of the two weaknesses',
    ],
    paragraphs: [
      'The Two Weaknesses Principle is the most powerful converting technique at grandmaster level. With one weakness the opponent can defend; with two weaknesses on opposite wings their pieces face an impossible choice. Defending weakness A allows weakness B to fall; defending B allows A to be exploited. Karpov made this the defining mechanism of his entire chess career — it appears in the majority of his winning endgames.',
      'Classic execution: win a pawn on one wing (weakness A), then create a passed pawn on the opposite wing (weakness B). The defender\'s rooks must split. The most efficient weapon is a queen or bishop controlling both flanks simultaneously — threatening weakness A and weakness B with the same piece. Timing is critical: do not create weakness B until weakness A is firmly established.',
      'The subtlest application of the principle: use the threat of creating weakness B as a tactical lever even when you don\'t intend to execute it. Threatening Rxg6 (weakness B) forces defensive pieces toward the kingside; this loosens the queenside around weakness A. The mere existence of a second threat — even if never played — overloads the defensive apparatus. World-class players describe this as "playing on both wings simultaneously."',
    ],
    famousNote: 'Karpov vs. Kasparov, World Championship 1985, Game 19: Karpov created a weak d6-pawn (weakness A), fixed it with Ne5, then opened a second front on the kingside with g4-g5 (weakness B), leaving Kasparov with two indefensible targets on opposite wings. Analysts consider it the textbook example of the Two Weaknesses Principle executed at world-championship level.',
  },
  {
    id: 'mid-e4', category: 'middlegame',
    title: 'Dynamic Piece Sacrifice for Initiative',
    subtitle: 'Giving material to shatter coordination — correctly',
    level: 'advanced',
    fen: 'r1b2rk1/pp2qppp/2n1p3/3pP3/3P4/2PB1N2/PP3PPP/R2Q1RK1 w - - 0 13',
    keyPoints: [
      'A correct piece sacrifice has a concrete endpoint: forced mate, won endgame, or perpetual check',
      'Greek Gift (Bxh7+): classical conditions must all be met — knight on f3, queen active',
      'Always calculate to a final position that is statically evaluable',
      '"Every move of the attacker must threaten — never give the defender a free move"',
      'A sacrifice with only drawing compensation is only correct when losing without it',
    ],
    paragraphs: [
      'The classical attacking sacrifice at grandmaster level is not speculative — it is backed by deep calculation to a concrete endpoint. The Greek Gift (Bxh7+ Kxh7, Ng5+ Kg8/Kh6, Qh5) is the most studied, but the conditions must all be exact: knight on f3 able to reach g5 in one move, queen able to join on h5, and no defensive resource like ...Qe7 or ...g6 blocking the attack. A single defensive resource breaks the sacrifice.',
      'More sophisticated is the structural piece sacrifice — giving a piece for 3 pawns and a permanent structural advantage. In the King\'s Indian Defense, Black sometimes sacrifices a piece on d4 or e3 to shatter White\'s center, leaving a dominant bishop pair and open files as compensation. At grandmaster level, these sacrifices are routinely calculated 10-15 moves deep to a statically evaluable final position.',
      'The critical discipline: always calculate to a position that you can evaluate without further tactics. If your combination ends in "a complicated position where I have the initiative" — that is not a concrete calculation endpoint. You need: checkmate, a material count where you are objectively ahead, or a perpetual check that saves the game. Stopping the calculation prematurely at a "dynamic compensation" assessment is the most common error in attacking chess.',
    ],
    famousNote: 'Kasparov vs. Topalov, Wijk aan Zee 1999: Kasparov sacrificed a rook on move 24 and calculated a 14-move forcing sequence leading to a won position. Deep Blue analysts confirmed the sacrifice was correct — but only 14 moves deep. Kasparov remarked: "I saw the endpoint first, then verified the path. Most players reverse that — and stop too early."',
  },
  {
    id: 'mid-e5', category: 'middlegame',
    title: 'Piece Domination & Restraint',
    subtitle: 'Making the opponent\'s best piece a spectator',
    level: 'advanced',
    fen: 'r4rk1/pp1q1pp1/2n1p2p/2ppP3/3P1B2/2PB1N2/PP3PPP/R2Q1RK1 w - - 0 14',
    keyPoints: [
      'Domination: position your pieces so the opponent\'s pieces have no useful square',
      'A dominated knight with no outpost is worth less than a pawn in practice',
      'Restrict the opponent\'s best piece first — often a fianchettoed bishop or central knight',
      'Blockade: place a piece on the promotion square of a passed pawn to neutralise it completely',
      'Once pieces are dominated, pawns advance freely — the positional bind becomes material',
    ],
    paragraphs: [
      'Piece domination is Nimzowitsch\'s most advanced concept. The goal is not merely to have active pieces — it is to make the opponent\'s pieces completely passive and useless. A knight with no squares to jump to is a prisoner. A bishop locked behind its own pawns on a closed color is a "tall pawn." When you achieve domination of even one key enemy piece, the resulting imbalance often decides the game without any further tactics.',
      'Practical technique: identify the opponent\'s most dangerous piece and systematically restrict it. Place pawns on the same color as an enemy bishop to close its diagonals. Place your pieces on squares the enemy knight wants. Trade your passive pieces for the opponent\'s active ones, leaving the dominated piece on the board. Once domination is complete, convert it to material advantage by forcing the opponent to give up the dominated piece for nothing useful.',
      'The highest form of restraint is the "positional bind" — a situation where the opponent has moves but no constructive plan. Their position deteriorates with every move. Karpov was the undisputed master: in multiple World Championship games, he created positions where Kasparov had moves but could not improve anything. Kasparov described the experience: "I could move, but every move made things worse. There was no active plan — only waiting to lose more slowly." That despair is the final product of perfect piece domination.',
    ],
    famousNote: 'Nimzowitsch\'s "My System" (1925) introduced restraint and blockade as systematic concepts — ideas 50 years ahead of their time. Carlsen has specifically cited Nimzowitsch\'s piece restraint as a major influence on his grinding style, which produces wins from objectively equal positions that no other player at 2800+ could convert.',
  },

  // ── ENDGAME ELITE (FIDE 3200+) ───────────────────────────────────
  {
    id: 'end-e1', category: 'endgame',
    title: 'Triangulation & Corresponding Squares',
    subtitle: 'King maneuvering to achieve zugzwang',
    level: 'advanced',
    fen: '8/8/4k3/8/4K3/4P3/8/8 w - - 0 1',
    keyPoints: [
      'Triangulation: maneuver your king via 3 squares to "waste" a tempo',
      'Corresponding squares: each critical king square has one the opponent must mirror',
      'Used when direct opposition fails — the king approaches from a wider angle',
      'The king with more maneuvering space can always triangulate; the restricted king cannot',
      'At 3200+ level, corresponding square analysis replaces calculation in K+P endings',
    ],
    paragraphs: [
      'Triangulation is the technique of moving the king via a three-square triangle (e.g., e4→d4→d3→e3 in three moves instead of the direct two) to "lose a tempo" deliberately, transferring the obligation to move to the opponent. This is critical in king-and-pawn endgames where zugzwang is the winning mechanism but direct opposition doesn\'t achieve it — the king takes the long way around, arriving at the same square with the opponent now to move.',
      'Corresponding squares (also called "related squares") is the systematic theory behind triangulation. For every critical square your king can occupy, there is a corresponding square the enemy king must occupy to maintain the defense. If you reach your critical square while your opponent cannot reach their corresponding square — because you triangulated successfully — you win the zugzwang battle. Mapping corresponding squares for a given pawn structure is an analytical skill that separates 2400+ from 2600+.',
      'The practical method: (1) Identify the key squares that win if your king reaches them. (2) Identify the squares the opponent\'s king must occupy to prevent this. (3) Determine if triangulation is possible by checking who has more maneuvering space. The king with more squares can triangulate; the king without cannot respond. Grandmasters perform this analysis in seconds — it is pattern recognition built from thousands of endgame positions studied.',
    ],
    famousNote: 'Reuben Fine\'s "Basic Chess Endings" devoted an entire chapter to corresponding squares, calling it "the most intellectually demanding concept in endgame theory." Magnus Carlsen has stated that corresponding square analysis is one of the first endgame topics he studied after mastering basic checkmates — he considers it mandatory knowledge for any player above 2000.',
  },
  {
    id: 'end-e2', category: 'endgame',
    title: 'Queen vs Rook — Converting the Theoretical Win',
    subtitle: 'Up to 35 moves of precision required',
    level: 'advanced',
    fen: '8/8/8/3k4/8/8/8/3KQ3 w - - 0 1',
    keyPoints: [
      'Q vs R is theoretically won in most positions — but requires up to 35 precise moves',
      'Technique: drive the king to the edge, then separate king from rook via skewer or fork',
      'The rook defends by staying adjacent to its king — the "shield" formation',
      'Your own king must participate — the queen alone cannot force checkmate',
      'In time trouble, even grandmasters have failed to convert: know the technique cold',
    ],
    paragraphs: [
      'Queen vs Rook is theoretically winning but practically one of chess\'s most demanding endgames. The rook defends by staying adjacent to its king, creating a "shield" against queen skewers and forks. The queen cannot simply attack the rook directly — she must first drive the enemy king to the edge, then create geometry where the rook is separated from its king at the critical moment.',
      'The winning procedure: (1) Force the enemy king to the edge with queen checks — use the queen to cut off escape squares. (2) Position your own king to join the final assault. (3) Use the queen to "fork" or "skewer" the king-rook pair by controlling the line between them. The classic winning idea: position the queen so that after a rook check, the king must step away from the rook, exposing it to capture. The Philidor-Lolli position and its variants are the theoretical foundation that every 2400+ player must know.',
      'Practical danger: under time pressure, even grandmasters have failed to convert Q vs R. Anand in the 2010 World Chess Championship Blitz reached a winning Q vs R and could not finish within the time control. The theoretical maximum is 35 moves under the 50-move rule — in rapid chess, this is often insufficient. Master this technique by replaying Karpov\'s three Q vs R conversions from World Championship matches.',
    ],
    famousNote: 'Vasily Smyslov (World Champion 1957-58) was considered the finest technical endgame player of his era. His Q vs R win against Botvinnik in their 1954 match — finding the precise queen maneuver on move 62 that separated king from rook — is still cited in FIDE Arbiter training materials as the reference example for this theoretical ending.',
  },
  {
    id: 'end-e3', category: 'endgame',
    title: 'Rook Endgame Mastery — Beyond Lucena & Philidor',
    subtitle: 'Advanced converting and saving techniques at elite level',
    level: 'advanced',
    fen: '8/5pk1/6p1/5pP1/5P2/8/5K2/6R1 w - - 0 1',
    keyPoints: [
      'Active king is worth a pawn in any rook endgame — centralize it immediately',
      'Rook on the 7th rank ("pig"): attacks pawns, restricts king, supports passers simultaneously',
      'Saavedra position: underpromotion to rook wins where queen promotion draws',
      'Pawn breaks at the right moment release the winning advantage — timing is everything',
      'Always calculate whether underpromotion avoids stalemate before queening',
    ],
    paragraphs: [
      'Beyond the Lucena and Philidor positions, rook endgames at the elite level require mastery of king activity. In virtually every rook endgame, the side with the more active king wins regardless of material equality. An active king on the 5th rank supporting connected passers is usually unstoppable. The defending side must use the rook to check from the side — but this only works if there is enough space for lateral checks to be effective.',
      'The 7th-rank rook ("pig") is one of the most powerful endgame weapons. A rook on the 7th simultaneously attacks undeveloped pawns, restricts the enemy king to the back rank, and supports passed pawns from behind. Doubled rooks on the 7th often produce an immediate decisive advantage. At grandmaster level, securing the 7th rank is the first priority in any simplified endgame — even at the cost of a pawn.',
      'The Saavedra position teaches the critical lesson: always calculate whether underpromotion to a rook (or bishop) avoids stalemate or wins material that queening does not. The famous Saavedra composition (1895) shows rook promotion winning where queen promotion draws — a concept that appears in practical games more often than most players expect. Every 2400+ player should have this pattern memorized cold, including the exact defensive resources it defeats.',
    ],
    famousNote: 'Bobby Fischer said: "Rook endgames are not studied enough by any player below master level." His own rook endgame technique was legendary. In the 1972 World Championship Game 6, Fischer converted a rook-pawn endgame that two grandmaster analysts had annotated as a draw — his winning method was extreme king activity and 7th-rank rook domination, both principles he had studied obsessively.',
  },
  {
    id: 'end-e4', category: 'endgame',
    title: 'Zugzwang in Complex Endgames',
    subtitle: 'Engineering positions where any move loses',
    level: 'advanced',
    fen: '8/pp6/k7/8/KP6/8/P7/8 w - - 0 1',
    keyPoints: [
      'Zugzwang: being forced to move is a disadvantage — the one to move loses',
      'Mutual zugzwang: both sides prefer not to move; the side to move loses',
      'Trébuchet: a specific pawn zugzwang — whoever moves loses regardless of whose turn it is',
      '"Reserve tempo" pawn move: keep one pawn move in reserve to shift the obligation to move',
      'Plan zugzwang positions 15-20 moves in advance — it is always a long-range maneuver',
    ],
    paragraphs: [
      'Zugzwang ("compulsion to move" in German) is one of chess\'s most counterintuitive and powerful concepts. In a zugzwang position, the player to move is at a disadvantage — any move worsens their position. In endgames, zugzwang determines whether a position is won or drawn far more often than most players realize. Recognizing and engineering zugzwang is a deep skill that separates 2400+ players from 2800+ players.',
      'The "reserve tempo" technique is essential for creating zugzwang. In pawn endings, keep one pawn move in reserve (e.g., a pawn on a4 still able to advance to a5). When you need to waste a tempo to transfer the move obligation, play that reserve pawn move. Without reserve tempos, you cannot triangulate with pawns (only with the king, and only if you have the maneuvering space). At grandmaster level, counting reserve tempos is a standard part of every pawn ending assessment.',
      'The Trébuchet is the purest form of mutual zugzwang: both kings and both pawns in a fixed formation where whoever must move loses — the king must give way, allowing the enemy king to invade. Engineers these positions requires calculating king trajectories 20+ moves in advance. Capablanca was the first player to systematically engineer Trébuchet positions in practical play, recognizing them as a game-deciding pattern rather than a theoretical curiosity.',
    ],
    famousNote: 'Capablanca vs. Tartakower, London 1924: 10 moves of pure king maneuvering designed to create a zugzwang position before even touching a pawn. Fischer described it as "the most profound king maneuver I have ever seen." FIDE Grandmaster Dvoretsky used this game as the opening lesson in his legendary endgame training camps for candidates-level players.',
  },
  {
    id: 'end-e5', category: 'endgame',
    title: 'Complex Endgame Decision-Making',
    subtitle: 'Choosing which pieces to trade and which endgame to enter',
    level: 'advanced',
    fen: 'r4rk1/pp2ppbp/6p1/q2p4/3P4/1QN2N2/PP2PPPP/R4RK1 w - - 0 14',
    keyPoints: [
      'The decision to enter an endgame requires the same calculation depth as a combination',
      'Not all material-equal endgames are drawn — pawn structure decides everything',
      'Trade into endgames where your king is more active or your pawn structure is superior',
      'Identify the "critical piece trade" — the one exchange that makes your endgame winning',
      'Queen endgames are highly tactical — often harder to convert than rook endgames',
    ],
    paragraphs: [
      'Elite endgame play begins before the endgame: in the decision of which pieces to trade. The player who understands endgame structures steers the middlegame toward the endgame that favors their pieces, and away from the endgame that favors the opponent. This requires evaluating endgame structures with the same depth as middlegame structures — a skill explicitly examined in FIDE Grandmaster title norms.',
      'The principle of the "good trade": trade pieces when the resulting endgame favors you. If you have a passed pawn and your opponent has connected central pawns, trading rooks often wins — without rooks, the passer cannot be stopped. If your opponent has the bishop pair in an open position, trading even one bishop changes the endgame character completely. Every planned piece trade must be evaluated in terms of its endgame consequence, not its middlegame effect.',
      'Queen endgames deserve special study because they are the most common and most counterintuitive endgame type. A material advantage in a queen endgame often provides fewer winning chances than the same advantage in a rook endgame, because queens create perpetual check threats so easily. In the 2021 World Championship, Nepomniachtchi vs Carlsen reached a queen ending in game 6 where Nepo had an extra pawn but perpetual check defensive resources made the win difficult — Carlsen eventually converted after 136 moves, the longest World Championship game ever.',
    ],
    famousNote: 'Mark Dvoretsky\'s "Endgame Manual" is the definitive text on elite endgame decision-making. Dvoretsky trained candidates including Yusupov and Dolmatov, writing: "Endgame technique is not memorization — it is the ability to identify the correct plan and execute it with precise calculation under pressure. The endgame is where the game is truly decided, and where the difference between 2600 and 2800 is most clearly visible."',
  },

  // ── PSYCHOLOGY ELITE (FIDE 3200+) ────────────────────────────────
  {
    id: 'psy-e1', category: 'psychology',
    title: 'Opening Preparation & Theoretical Novelties',
    subtitle: 'The weapon that wins World Championships before move 1',
    level: 'advanced',
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    keyPoints: [
      'A theoretical novelty (TN) is a prepared improvement over known theory',
      'Novelties at move 20+ require months of home preparation and engine analysis',
      'Psychological impact: a strong novelty forces the opponent to think from scratch',
      'Prepare counter-novelties too — anticipate what the opponent has prepared',
      '"The best players prepare for what the opponent has never considered" — Kasparov',
    ],
    paragraphs: [
      'At the 3200+ level, opening preparation is a weapon as powerful as tactical calculation. A well-prepared novelty at move 22 leaves a 2800-rated opponent with 45 minutes to calculate what you spent 3 months analyzing at home. The psychological effect is devastating: the opponent must solve a completely new problem at the board while you play prepared moves at speed. This time-pressure advantage compounds throughout the game.',
      'The preparation method: (1) Identify the opponent\'s most likely opening choice from database analysis of their recent games. (2) Find the critical theoretical position where the main line exists. (3) Analyze deeply — looking for improvements engines may miss because they require non-obvious human ideas. (4) Prepare at least 10 moves past the novelty. (5) In the game, play quickly through known territory, then "hesitate" slightly at the novelty to disguise the depth of your preparation.',
      'Counter-preparation is equally important. Before a World Championship game, top players not only prepare their own novelties but anticipate the opponent\'s possible novelties and prepare responses. Carlsen\'s team prepares "emergency protocols" — if a novelty appears, the predetermined response is a safe move avoiding complications, buying time to think. This preparation-within-preparation is the cutting edge of professional chess at 2800+.',
    ],
    famousNote: 'Kasparov\'s novelty 13.Nd5!! in the Sicilian Najdorf against Topalov (Linares 1999) was prepared with his team. Topalov spent 70 minutes on his response and never equalized. Kasparov wrote: "The preparation was so deep that I played the next 12 moves almost instantly. Topalov saw me playing fast and knew he was in serious trouble — the psychological pressure was as damaging as the objective position."',
  },
  {
    id: 'psy-e2', category: 'psychology',
    title: 'Psychological Warfare at the Elite Level',
    subtitle: 'The mental battle that happens away from the board',
    level: 'advanced',
    fen: 'rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1',
    keyPoints: [
      'The game begins before move 1: opening choice is a psychological message',
      'Kasparov\'s method: aggression forces opponents into uncomfortable territory',
      'Karpov\'s method: patience and neutrality — let opponents defeat themselves',
      'Fischer\'s method: total domination — impose your style and never accommodate',
      'Carlsen\'s method: play past the objective draw boundary into practical complexity',
    ],
    paragraphs: [
      'At World Championship level, chess is as much psychological as technical. The choice of opening sends a message: the Sicilian Dragon signals "I will fight to the death"; the Berlin Defense signals "I will neutralize and grind for 80 moves." Kasparov chose openings based on his assessment of each opponent\'s psychological weaknesses. Against passive players, he played the most aggressive structures; against calculating specialists, he chose closed positions that denied them tactical opportunities.',
      'Fischer\'s psychological method was total domination. He played only his best moves, never accommodating the opponent, and expected everyone to operate at his level or fail. He refused draws in equal positions because he believed his technique was superior in any endgame. This was not arrogance — it was a calculated strategy. Knowing an opponent expects a draw offer and doesn\'t receive one creates enormous psychological pressure, often leading to errors in positions they had considered safe.',
      'Carlsen\'s modern method is the most sophisticated: he plays past the objective drawing horizon, creating positions that are theoretically equal but practically complex, relying on superior practical decision-making. His opponents know the position is drawn but also know Carlsen will outplay them in complications. The effect is paralysis — they cannot play for a draw (Carlsen will refuse) and cannot play for a win without taking risks. This "pressure in equal positions" is the defining feature of 2850+ chess.',
    ],
    famousNote: 'Kasparov vs. Karpov, World Championship 1984-86: the greatest psychological chess battle in history. After 5 matches and 144 games, Kasparov said: "Karpov was the only opponent who made me genuinely afraid at the board — because he never showed emotion and I never knew what he was thinking. His coldness was itself a psychological weapon."',
  },
  {
    id: 'psy-e3', category: 'psychology',
    title: 'The Must-Win Situation',
    subtitle: 'Playing for a win when a draw loses the match',
    level: 'advanced',
    fen: 'rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR b KQkq - 0 1',
    keyPoints: [
      'Must-win: a draw loses the match — you must take risks the position does not justify',
      'Choose the most unbalanced opening available — surprise the opponent\'s preparation',
      'Avoid early simplifications at all costs — keep all pieces on the board',
      'Create asymmetric pawn structures that require both sides to play actively',
      'Maintain composure — never show desperation even when behind on the clock',
    ],
    paragraphs: [
      'A must-win game is chess\'s ultimate psychological test. When a draw loses the match, you must play for a win even in equal positions — which means deliberately choosing moves that are not objectively best but create maximum complexity. The core tension: the opponent knows you must win and will steer toward simplifications, while you must avoid these at all costs without appearing desperate.',
      'The must-win opening strategy: choose the most double-edged system available. If your opponent expects the Berlin (solid) and you must win, play the Najdorf or King\'s Indian — openings guaranteed to produce unbalanced play. If you normally play 1.d4, switch to 1.e4 for surprise value. The element of surprise carries both objective and psychological weight: the opponent must leave their preparation zone, costing clock time and confidence.',
      'The most critical psychological technique in a must-win game: do not show desperation. Continue your normal playing speed with normal body language. If you begin playing fast or show visible tension, your opponent senses blood and plays even more cautiously. Many must-win games have been saved by maintaining composure through a solid unbalanced opening for 15 moves, then finding the precise moment to inject maximum complications.',
    ],
    famousNote: 'Spassky in Game 3 of the 1972 World Championship played 1.d4 (instead of his usual 1.e4) in a must-win situation specifically to surprise Fischer. The psychological gambit worked — Fischer spent enormous time in the opening and eventually lost. Spassky explained: "Sometimes the best opening novelty is to change openings completely. Fischer had prepared against everything except what I actually played."',
  },
  {
    id: 'psy-e4', category: 'psychology',
    title: 'Thinking on Your Opponent\'s Time',
    subtitle: 'Doubling your effective calculation budget',
    level: 'advanced',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
    keyPoints: [
      'While your opponent thinks, pre-calculate your response to their most likely moves',
      '"If they play A, I play B. If A\', I play B\'" — prepared branches save your clock',
      'This technique doubles your effective thinking time without using your own clock',
      'Do not commit mentally before they play — always verify the actual move made',
      'Track 2-3 most likely opponent moves simultaneously, not just the most obvious one',
    ],
    paragraphs: [
      'Pre-move analysis — thinking on your opponent\'s time — is one of the most valuable skills separating professional players from amateurs. While your opponent is thinking, calculate your response to their most likely moves. By the time they play, you have already thought about the position for their entire thinking time, effectively doubling your time budget without spending your own clock.',
      'The method: when your opponent starts thinking, immediately ask: "What are the 2-3 most likely moves they will play?" Calculate your best response to each in parallel. If they play the most likely move (A), you play your prepared response instantly. If they play a surprise (B), you still have your full clock to recalculate. This approach means your clock only decreases when facing genuine surprises — all expected moves are handled for free.',
      'The crucial discipline: never commit mentally to a specific reply before they actually play. Many games are lost by "premove lock-in" — the player has decided their response, the opponent plays something unexpected, but the player executes their prepared move anyway out of premove momentum. Always verify the actual move played with fresh eyes. This 2-second check prevents potentially catastrophic blunders and is non-negotiable at any competitive level.',
    ],
    famousNote: 'Kasparov was renowned for pre-move analysis speed. Opponents described watching him calculate intensely during their own thinking time, then playing his response within 3 seconds of their move. Kramnik wrote: "Kasparov\'s intense focus during my thinking time was itself a form of psychological pressure. He was working harder than me even when it was my turn to move."',
  },
  {
    id: 'psy-e5', category: 'psychology',
    title: 'Recovering from Blunders — The Bounce-Back Mentality',
    subtitle: 'How world champions reset after catastrophic errors',
    level: 'advanced',
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    keyPoints: [
      'After a blunder: immediately clear all emotion — panic and self-criticism compound mistakes',
      'The "fresh slate": treat the new position as a completely new problem with no history',
      'Look for the best defensive resource — it almost always exists, even in lost positions',
      'Create maximum complications — force the opponent to calculate in unfamiliar positions',
      '"The game is never over until the resignation" — Fischer\'s defining philosophy',
    ],
    paragraphs: [
      'Recovering from a blunder is one of the most important and least-taught chess skills. After a catastrophic error, your psychological response determines whether you lose immediately or fight back to a possible save. The first and most critical step: immediately stop all emotional reaction — shock, self-criticism, frustration — and return to pure calculation. Every second spent on emotion is a second not spent finding a defensive resource.',
      'The "fresh slate" technique: instead of thinking "I had a winning position and now I\'ve ruined it," immediately reframe: "The current position is what it is. What is the best I can do from here?" This cognitive reset is practiced by every world champion. Kasparov described it as "amnesia between moves" — deliberately forgetting the previous position to evaluate the current one with completely fresh eyes and zero emotional residue.',
      'Practical fighting technique after a blunder: look for the most complicated continuation available. Even in lost positions, creating tactical threats forces the opponent to calculate and provides chances for counter-play or error. Many games at the highest level have been saved by creating extreme complications that the winning side failed to navigate correctly. Carlsen saved a losing position against Anand in the 2013 World Championship through relentless complication — forcing Anand into a critical time-pressure decision that he ultimately mishandled.',
    ],
    famousNote: 'Botvinnik (World Champion 1948-63) was famous for fighting back from setbacks. He lost Games 1 and 2 of his 1951 match against Bronstein, then fought back to a 12-12 draw to retain the title. He wrote: "A chess player is not judged by how he plays when things go well, but by how he plays when things go badly. The best players play their best chess in the worst situations."',
  },

  // ── THINKING ELITE (FIDE 3200+) ──────────────────────────────────
  {
    id: 'think-e1', category: 'thinking',
    title: 'Dynamic Evaluation — Beyond Material Counting',
    subtitle: 'How top players assess what engines cannot',
    level: 'advanced',
    fen: 'r1b2rk1/pp3ppp/2n1pq2/3p4/3P4/2N1BN2/PP2QPPP/R4RK1 w - - 0 14',
    keyPoints: [
      'Dynamic evaluation: who controls the game\'s direction, regardless of material count',
      'Factors: tempo advantage, lead in development, king safety differential, available pawn breaks',
      '"The threat is stronger than its execution" — threats restrict enemy options every move',
      'A 3-tempo development lead in an open position equals at least one pawn',
      'Engine evaluations often miss human dynamic factors — trust deep calculation in sharp lines',
    ],
    paragraphs: [
      'Static evaluation counts material. Dynamic evaluation asks: who controls the game? A player who is a pawn down but holds the initiative — forcing the game to follow their plan — is often practically better than the material count suggests. Three tempos of development advantage (three developed pieces vs. none) are worth at least a pawn in virtually any open game. A king safety advantage — your king castled, opponent\'s king exposed — is worth even more when the position opens.',
      'The principle of the initiative: when you have it, every threat forces your opponent to react. Their moves are all responses to yours — they cannot improve their position, only defend. Once you "own" the initiative, your practical task is to maintain it: always create a new threat before the current one is neutralized. The moment you make a passive move, you surrender the initiative and must rebuild it from scratch — often at material cost.',
      'The subtlest dynamic factor: the available pawn break. A player with a prepared ...d5 break (pawn on d6, White pawns fixed on e4/d4) has a "dynamic bomb" waiting. The threat of the break is often stronger than playing it — it restricts enemy pieces that must guard against it, while your own pieces operate freely. World-class players maintain at least one unplayed pawn break for the entire middlegame, releasing it only at the optimal moment.',
    ],
    famousNote: 'Mikhail Tal\'s evaluation was purely dynamic — he cared far more about initiative and threats than material. He said: "You must believe in the attack when the position demands it, even if the material count says otherwise." Modern engines validate his intuition: his famous "unsound" sacrifices frequently show correct evaluations — the dynamic compensation was real, just invisible to 1960-era analysis methods.',
  },
  {
    id: 'think-e2', category: 'thinking',
    title: 'Mastering the Initiative',
    subtitle: 'When to attack, consolidate, and switch flanks',
    level: 'advanced',
    fen: 'r2q1rk1/ppp2ppp/2n1pn2/3p4/3P4/2N1PN2/PPQ2PPP/R1B2RK1 w - - 0 9',
    keyPoints: [
      'The initiative is a clock: it expires if you fail to create threats every move',
      '"Attack where the opponent is weakest" — choose the flank where you dominate',
      'Flank switch: shift the attack from one wing to the other to overload the defense',
      'The anti-move: neutralize opponent\'s counterplay before launching your own attack',
      'Know when to "cash in": convert the initiative to material before it evaporates',
    ],
    paragraphs: [
      'The initiative is not a permanent asset — it is a flow that must be continuously renewed. Every move in an attack must either threaten something concrete or improve the attack\'s setup for the next threat. A "quiet" move that threatens nothing surrenders the initiative even if it looks positionally strong. Kasparov in his prime played threats on virtually every move in attacking positions — the opponent never received a free move to organize their defense.',
      'Flank switching is the most sophisticated attacking technique. After establishing kingside pressure, a sudden switch to queenside attack is devastating because the defender has concentrated pieces on king defense. The classic technique: create a concrete kingside threat (forcing defensive pieces to commit), then switch to the queenside with tempo. The queen is ideally suited for flank switches because of her range — she can threaten two flanks simultaneously.',
      'Knowing when to "cash in" the initiative is perhaps the most difficult judgment in chess. Players sometimes maintain an attack one or two moves too long — greedy for a brilliant combination — when a simpler material-winning line was available. The rule at 2800+ level: when the initiative gives you a clear material gain, take it. A pawn advantage in a technically won endgame is more reliable than a speculative attack requiring perfect follow-up from both sides.',
    ],
    famousNote: 'Kasparov\'s attacking philosophy was systematic: "Every move of mine should be threatening something. My opponent should never get a free move." In his prime (1986-1996), Kasparov lost only 1.4% of his classical games — largely because he maintained the initiative in virtually every position, converting initiative into material or mating attacks with clinical precision.',
  },
  {
    id: 'think-e3', category: 'thinking',
    title: 'The Forcing Tree — Calculating 15+ Moves Deep',
    subtitle: 'How world champions calculate accurately at maximum depth',
    level: 'advanced',
    fen: 'r1bq1rk1/ppp2ppp/2n1pn2/3p4/3PP3/2N2N2/PPP1BPPP/R1BQK2R w KQ - 0 7',
    keyPoints: [
      'Elite calculation focuses on FORCING lines: checks, captures, threats — in that order',
      'The CCT method: exhaust Checks, Captures, Threats before any quiet move',
      'The "trunk" is narrow: usually 1-2 critical forcing variations per position',
      'Eliminate branches immediately when a move clearly fails — never revisit them',
      'The endpoint must be statically evaluable — not "complicated with chances"',
    ],
    paragraphs: [
      'Elite calculation is not about calculating more variations — it is about calculating the right variations to the correct depth. The Checks-Captures-Threats (CCT) method is the foundation: first exhaust all checks (most forcing), then all captures, then all serious threats. This creates a narrow "forcing tree" where critical variations are fully mapped. Non-forcing side variations are only considered when the forcing tree yields nothing better.',
      'The key insight: in most tactical positions, only 1-2 moves are truly forcing. A check the opponent can only answer one way, a capture creating a specific material count, a threat that must be stopped immediately — these are the branches of the trunk. All other variations (quiet positional moves) belong to a different, far shallower level of analysis. Grandmasters navigate to the trunk instantly; everything else is background noise filtered out automatically.',
      'The calculation endpoint is critical. A combination must be calculated to a position you can evaluate statically — not a position that is "dynamic and unclear." If your combination ends in "a complicated position where I have the initiative," that is not a calculation endpoint — it is a stopping point masquerading as a conclusion. Real calculation endpoints are: checkmate, a material count that is objectively won, or a perpetual check that saves a lost game. Stopping before one of these is reached means your calculation is unfinished.',
    ],
    famousNote: 'Kasparov\'s famous game vs. Topalov (1999) involved a rook sacrifice on move 24 and a calculation sequence of 14 forcing moves to a won position. He said: "I saw the endpoint first — a won rook endgame on move 38 — then worked backward to verify the path was forced. Most players try to calculate forward and hope the position will be good. The best players start from the conclusion."',
  },
  {
    id: 'think-e4', category: 'thinking',
    title: 'Prophylaxis at Grandmaster Level',
    subtitle: 'Preventing threats before they become real',
    level: 'advanced',
    fen: 'r1bq1rk1/pp3ppp/2n1pn2/2pp4/3P4/2N1PN2/PPQ2PPP/R1B2RK1 w - - 0 10',
    keyPoints: [
      'Prophylaxis: ask "What is my opponent\'s best plan?" before choosing your own move',
      'A prophylactic move prevents the opponent\'s best idea before it can be executed',
      'Nimzowitsch called this "overprotection" — defend key points before they are attacked',
      'Every candidate move must be tested: "What is my opponent\'s best reply to THIS move?"',
      'At 3200+ level, prophylaxis is continuous — every move prevents something specific',
    ],
    paragraphs: [
      'Prophylactic thinking is one of the most important and most underused techniques at every level. Before choosing your own move, ask: "What is my opponent\'s best plan in this position? What are they threatening to do in the next 2-3 moves?" Then find a move that both advances your own plan AND prevents the opponent\'s best idea. At grandmaster level, every move serves double duty — it improves your position while simultaneously preventing something dangerous.',
      'Nimzowitsch\'s concept of "overprotection" is prophylaxis applied systematically: protect your key pieces, pawns, and squares beyond what is strictly necessary, so they can never become targets. An overprotected passed pawn — defended by rook, queen, and king — cannot be attacked profitably. An overprotected outpost knight — supported by pawn, bishop, and rook — cannot be traded off. This surplus of protection is not wasteful; it is the foundation of a stable, unassailable position.',
      'The critical habit: after choosing your "best" move, always ask "What is my opponent\'s best reply to THIS specific move?" If the answer is a devastating tactic or strong positional improvement, your move is wrong — go back and find the move that prevents that response. This "anti-move check" is mandatory at every competitive level but is most often neglected by players below 2000. At 3200+ level, it happens automatically on every single move.',
    ],
    famousNote: 'Karpov was considered the greatest prophylactic thinker in chess history. His rival Kasparov admitted: "Karpov always seemed to know what I was planning before I knew it myself. He prevented my ideas before they were fully formed. Playing him felt like playing against an opponent who could read my mind." This was the result of systematic prophylactic thinking applied at every move.',
  },
  {
    id: 'think-e5', category: 'thinking',
    title: 'The Principle of Two Plans',
    subtitle: 'Maintaining flexibility while your opponent commits',
    level: 'advanced',
    fen: 'r1b1r1k1/pp3ppp/2n1pq2/2pp4/3P1B2/2N1PN2/PP2QPPP/R4RK1 w - - 0 12',
    keyPoints: [
      'Never commit to a single plan when two plans are both available',
      'Force the opponent to commit while you maintain options — then choose against their commitment',
      'The "two plans" position: you can attack either wing depending on what opponent does',
      'Chess decisions are often not "what is best?" but "best given what the opponent does?"',
      'Strategic flexibility is a weapon — the opponent cannot prepare against two different threats',
    ],
    paragraphs: [
      'The Principle of Two Plans is one of the most sophisticated strategic concepts in elite chess. When you have two viable plans (e.g., kingside attack via g4-g5 or queenside pressure via c4-c5), do not immediately execute either. Instead, make a move that keeps both options open while forcing the opponent to commit their pieces to a defensive formation. Once they commit — bringing pieces to the kingside, for example — switch to the queenside plan immediately.',
      'This principle is related to the concept of "keeping the tension." Prematurely resolving pawn tension (e.g., capturing on c5 when you could maintain pressure) often eliminates one of your two plans and makes the opponent\'s defense easier. World champions maintain pawn and piece tension as long as possible, forcing the opponent to make defensive decisions that can be exploited. "Never capture unless the capture wins something or relieves genuine pressure" is a grandmaster axiom.',
      'The deepest application: two-plan thinking at the strategic level. A player who can credibly threaten both a kingside attack and a queenside expansion forces the opponent to defend everywhere simultaneously — which is impossible. Kasparov described it as "keeping the opponent on the horns of a dilemma." The only resolution for the defender is to create their own counterplay, but finding active counterplay while defending two threats requires a calculation depth and energy that most players cannot sustain under time pressure.',
    ],
    famousNote: 'Garry Kasparov\'s game preparation included systematically identifying positions with "dual threats" — where he could credibly play on either wing. His trainer Botvinnik taught him: "The player who can threaten two things simultaneously forces the opponent to make a positional concession. The player who has only one plan has already been half-defeated." This two-plan principle underpins much of Kasparov\'s attacking genius.',
  },
]

export const CATEGORIES: { id: Category; label: string; color: string; desc: string }[] = [
  { id: 'openings',   label: 'Openings',   color: 'amber',  desc: '5 opening systems (beginner–advanced)' },
  { id: 'middlegame', label: 'Middlegame', color: 'blue',   desc: '10 lessons · tactics to elite strategy' },
  { id: 'endgame',    label: 'Endgame',    color: 'green',  desc: '10 lessons · technique to 3200+ mastery' },
  { id: 'psychology', label: 'Psychology', color: 'purple', desc: '10 lessons · mindset to World Championship' },
  { id: 'thinking',   label: 'Thinking',   color: 'rose',   desc: '10 lessons · routine to elite calculation' },
]
